Added post for this week
stevenpi/Link.MD.Lerndoku pull request #17
Opened 2018-06-29 14:31 UTC by stevenpi

2018-07-02 09:05 UTC, mbaechtold requested changes

2018-07-02 09:05 UTC, mbaechtold commented on 2018-06-29.md
> +Wie schon so oft, musste ich mich heute auch ein wenig aufregen. An einem Issue, dem Issue [# vom RIS Projekt](), benötigte ich viel zu lange zum Verstehen, was eigentlich abgeht. Schlussendlich benö
Hier fehlt noch die Issue-Nummer und der Link zum Issue.

2018-07-06 12:12 UTC, stevenpi commented
Habe die Issue nummer und den Link eingefügt

2018-07-06 12:27 UTC, mbaechtold approved these changes
Danke!

2018-07-06 12:32 UTC, merged