Added post for last week
stevenpi/Link.MD.Lerndoku pull request #7
Opened 2018-04-09 08:12 UTC by stevenpi

2018-04-09 08:19 UTC, mbaechtold requested changes

2018-04-09 08:19 UTC, mbaechtold commented on 2018-04-06.md
> +## 2018-04-08
Wäre das nicht eher 2018-04-02, also der Montag der KW 14?

2018-04-13 14:52 UTC, stevenpi commented
Habs ausgebessert und nun auch den Post für diese Woche hinzugefügt.

2018-04-13 15:37 UTC, mbaechtold approved these changes
Merci Steven und schöne Ferien!

2018-04-30 05:07 UTC, merged